// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArtFAajosOLA4nN0V268lFWgJjs3Cfv1g',
    appId: '1:717949916868:web:f061e8f6bc792255b85b91',
    messagingSenderId: '717949916868',
    projectId: 'notes-b4757',
    authDomain: 'notes-b4757.firebaseapp.com',
    storageBucket: 'notes-b4757.appspot.com',
    measurementId: 'G-FCT1S1Y3HF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKJBB6QYspmg-iG0C1qh3fVr2ogXdao6o',
    appId: '1:717949916868:android:0fd53be832830ec6b85b91',
    messagingSenderId: '717949916868',
    projectId: 'notes-b4757',
    storageBucket: 'notes-b4757.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFy1Arx-PxQaPOeR8BihxsEUvobGqFsc8',
    appId: '1:717949916868:ios:d7cead438bbec2d9b85b91',
    messagingSenderId: '717949916868',
    projectId: 'notes-b4757',
    storageBucket: 'notes-b4757.appspot.com',
    iosClientId: '717949916868-as5am5jj92ac6mga0ps3tmndhd5tvrvu.apps.googleusercontent.com',
    iosBundleId: 'com.cahliksoftwaresolutions.notes',
  );
}
